# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-08-06 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_last_login_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.CharField(default='2001-01-01', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='graduate_time',
            field=models.CharField(default='2022-06-01', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(default='软件工程师', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='job_number',
            field=models.CharField(default='0001', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='job_time',
            field=models.CharField(default='2020-07-01', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='第一次登陆', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='12345799315', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(default='武汉大学', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(default='男', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='team_belong',
            field=models.CharField(default='C401', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='xueli',
            field=models.CharField(default='本科', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='zhengzhi_mianmao',
            field=models.CharField(default='群众', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='zhengzhi_shijian',
            field=models.CharField(default='2020-01-01', max_length=20),
        ),
    ]
